### ISSUE TITLE
Change project file format

### ISSUE THREAD

**Issue by lewisakura** [ByteCrafter/Craftbyte-Mod-IDE#14]
The current file format actually conflicts with a game-kinda-thing called Powder Toy. You are technically writing a Powder Toy Save file which will conflict with CMI if you decide to use VS file extensions.

**Comment by ByteCrafter** [comment]
It's CPS, not CMI actually. CPS stands for "Craftbyte Mod IDE Project Solution File".

**Comment by lewisakura** [comment]
I didn't mean that... What I meant by CMI is Craftbyte Mod IDE, not the file format. It will conflict anyhow as Powder Toy uses CPS for it's file format.

**Comment by ByteCrafter** [comment]
Lol, okay. I am currently a bit confused now because of an other Project xD

**Comment by ByteCrafter** [comment]
Will change.

**Comment by lewisakura** [comment]
Thank you.

**Comment by ByteCrafter** [comment]
No problem. :)

**Comment by lewisakura** [comment]
:)

**Comment by ByteCrafter** [comment]
Fixed.
